### ISSUE TITLE
renter can't contact IP 172.17.0.1 from docker: time out

### ISSUE THREAD

**Issue by cldxeu** [mtlynch/docker-sia#30]
host.log give a lot of errors : 1.3.2 1.3.3 1.3.3b: interface 172.17.0.x from docker: using a synology  6.1.7

2018/07/05 07:58:51.167725 errors.go:151: connection error: error with 172.17.0.1:46428: incoming RPCReviseContract failed: revision iteration failed: could not read renter transaction signature: EOF
2018/07/05 08:03:01.592197 errors.go:151: connection error: error with 172.17.0.1:47105: incoming RPCReviseContract failed: failed RPCRecentRevision during RPCReviseContract: could not read challenge response: read tcp 172.17.0.3:9982->172.17.0.1:47105: i/o timeout
2018/07/05 08:15:23.064478 errors.go:151: connection error: error with 172.17.0.1:47223: incoming RPCReviseContract failed: revision iteration failed: unable to read revision modifications: read tcp 172.17.0.3:9982->172.17.0.1:47223: i/o timeout
2018/07/05 08:29:32.396835 errors.go:151: connection error: error with 172.17.0.1:47621: incoming RPCReviseContract failed: revision iteration failed: unable to read revision modifications: read tcp 172.17.0.3:9982->172.17.0.1:47621: i/o timeout
2018/07/05 08:41:58.928295 errors.go:151: connection error: error with 172.17.0.1:48130: incoming RPCReviseContract failed: revision iteration failed: could not read renter transaction signature: EOF
2018/07/05 08:56:03.467428 errors.go:151: connection error: error with 172.17.0.1:48519: incoming RPCReviseContract failed: revision iteration failed: could not read renter transaction signature: EOF
2018/07/05 09:04:14.067739 errors.go:151: internal error: error with 172.17.0.1:48837: incoming RPCReviseContract failed: failed RPCRecentRevision during RPCReviseContract: challenge failed: could not get xxxxxxxxxxxxxxxxxxxxxxxxxx lock: the requested file contract is currently locked
2018/07/05 09:04:23.829255 errors.go:151: communication error: error with 172.17.0.1:48582: incoming RPCReviseContract failed: revision iteration failed: rejected proposed modifications: unable to verify updated contract: host expected to post at most xxxxxxxxxxxxxxxxxxxx collateral, but contract has host posting xxxxxxxxxxxxxxxxxx: rejected for low paying host missed output
2018/07/05 09:16:45.988936 errors.go:151: communication error: error with 172.17.0.1:49673: incoming RPCFormContract failed: contract verification failed: renter proposed a file contract with a too-long duration
2018/07/05 09:19:06.821177 errors.go:151: connection error: error with 172.17.0.1:49011: incoming RPCReviseContract failed: revision iteration failed: could not read renter transaction signature: EOF
2018/07/05 09:28:25.989285 errors.go:151: connection error: error with 172.17.0.1:50266: incoming RPCReviseContract failed: revision iteration failed: could not read renter transaction signature: EOF

**Comment by mtlynch** [comment]
There's nothing wrong with your Sia node or the Docker image. It's just a peer that is misconfigured, so it's generating errors when it tries to communicate with your node.

**Comment by cldxeu** [comment]
OK, i tought my host was sending bad settings to some renters.

Le jeu. 5 juil. 2018 à 23:08, Michael Lynch <notifications@github.com> a
écrit :
