### ISSUE TITLE
Cant set --user=uid:gid in docker run command

### ISSUE THREAD

**Issue by polpas** [mtlynch/docker-sia#47]
When I set --user=uid:gid in docker run command the container fails to start. Is there a way to set permissions to a user:group at docker instead of running with high privilege account?

**Comment by mtlynch** [comment]
It should be possible to add a standard user account to run Sia in the `Dockerfile`. I'll experiment this week to make sure it doesn't break anything.

**Comment by mtlynch** [comment]
Sorry, I tried to get this working, but wasn't able to:

https://github.com/mtlynch/docker-sia/tree/std-user

The trick is that if the user is mounting volumes (which they probably will be), then you need commands at runtime that chown the mounted volumes to the sia user and then switch execution context to the Sia standard user. But then you end up with confusing permissions issues on the mounted volume.

I won't have bandwidth to investigate this further for a while, but you're welcome to experiment and reopen if you're able to find a working solution.
