### ISSUE TITLE
Sia update 1.4.3

### ISSUE THREAD

**Issue by PNRxA** [mtlynch/docker-sia#48]
Sia v1.4.3 is out with support for Sia Skynet, can you update the dockerfile to this version?

**Comment by mtlynch** [comment]
Thanks for the heads up! I've [tried to get them to send out release announcements](https://www.reddit.com/r/siacoin/comments/evcdcv/sia_v1421_is_here/ffy0v9l/) the day of new releases, but they've so far insisted on delaying it a few days for some reason.

**Comment by PNRxA** [comment]
@mtlynch Thanks for getting it out so quick! In regards to getting alerted of new releases, I monitor my host with https://siastats.info/hosts and it sends you an email when you're running an out of date Sia client :)
