### ISSUE TITLE
How to pass url parameter instead IP

### ISSUE THREAD

**Issue by polpas** [mtlynch/docker-sia#50]
I would like to pass a URL parameter for the annoucement of sia in the creation of the docker. How to do that?

**Comment by mtlynch** [comment]
Sorry, I'm having trouble understanding this request. Can you tell me more about what you're trying to do?

**Comment by polpas** [comment]
I would like to publish  a domain name example coto.world.com so dia is discoverable through it Is it possible?

Francisco R. Martins

**Comment by mtlynch** [comment]
You can use the `siac host announce coto.world.com:9982` but that's just a feature of Sia and is not related to the Docker image.

This repo is specifically for the Docker image for Sia. For questions about using Sia, you can get support via [their official support channel](https://discord.gg/sFCT3Ar).
