### ISSUE TITLE
Could not unlock wallet: [POST request error; API authentication failed.]

### ISSUE THREAD

**Issue by polpas** [mtlynch/docker-sia#51]
After upgrading to latest version when I try to unlock wallet it gives this error:

Could not unlock wallet: [POST request error; API authentication failed.]

I changed wallet folder name so application crates an ew one but error persists.

**Comment by mtlynch** [comment]
This issue does not seem to be related to the Docker image. For questions about using Sia, you can get support via [their official support channel](https://discord.gg/sFCT3Ar).
