### ISSUE TITLE
Allow specifying custom command args

### ISSUE THREAD

**Issue by Derkades** [mtlynch/docker-sia#54]
Particularly, I'd like to set `--authenticate-api=false` so I can connect to the container from Sia-UI.

I've tried the `command` and `entrypoint` options in docker-compose but that didn't seem to do what I want. Maybe add an environment variable that is appended to the command string?

**Comment by mtlynch** [comment]
Thanks for the suggestion! I'm unfortunately [ending support for the Sia Docker image](https://redd.it/ftxcd4), so I'll need to close this.
